spring:
  kafka:
    bootstrap-servers: kafka1:9092
    client-id: 1
  cloud:
    stream:
      bindings:
        input:
          destination: file-topic
          content-type: application/*+avro
        output:
          destination: file-topic-non-dup
          content-type: application/*+avro
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://kafka-schema-registry:8081
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://kafka-schema-registry:8081
            specific.avro.reader: true
